services: # 컨테이너 설정
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${}   # 루트 비밀번호 설정
      MYSQL_DATABASE: ${}              # 기본 데이터베이스 이름
      MYSQL_USER: ${}                 # 사용자 이름
      MYSQL_PASSWORD: ${}         # 사용자 비밀번호
    ports:
      - "33306:33306"                        # 호스트와 컨테이너의 포트 매핑
    volumes:
      - mysql_data_dev:/var/lib/mysql          # 데이터 볼륨 설정

  backend:
    container_name: gaji-server-dev
    image: ${}
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 8000:8000

volumes:
  mysql_data_dev:                      # mysql_data 볼륨 정의